# Generated by Django 5.0.6 on 2024-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_categoria_productocategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_doc',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
