# Generated by Django 5.0.6 on 2024-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_precio_producto_precio_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_doc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
