# Generated by Django 5.0.6 on 2024-05-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0002_rename_categoria_productocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Entregado', 'ENTREGADO'), ('Pendiente', 'PENDIENTE'), ('Cancelado', 'CANCELADO')], default='Pendiente', max_length=10)),
                ('hora', models.TimeField(editable=False)),
                ('direccion', models.CharField(max_length=100)),
                ('cliente', models.TextField(blank=True, max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('Efectivo', 'EFECTIVO'), ('Transferencia', 'TRANSFERENCIA'), ('Debito', 'DEBITO'), ('Cobrar', 'COBRAR'), ('Pago', 'PAGADO')], default='Cobrar', max_length=13)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.producto')),
            ],
        ),
    ]
