# Generated by Django 5.0.6 on 2024-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_cliente_alter_pedido_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(choices=[('Efectivo', 'P. EFECT'), ('Transferencia', 'P. TRANSF'), ('Debito', 'P. DEBITO'), ('Cobrar', 'COBRAR')], default='Cobrar', max_length=13),
        ),
    ]
