# Generated by Django 5.0.6 on 2024-05-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_medio_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='medio_pago',
            new_name='pago',
        ),
    ]
